# Bem-vindo {.unnumbered}

Este é o website de tradução do trabalho-em-andamento da segunda edição de "**R for Data Science**".
Este livro lhe ensinará como fazer ciência de dados com R: Você aprenderá como trabalhar seus dados no R, colocando-os em uma estrutura muito mais útil, transformando-os e visualizando-os.

Neste livro, você encontrará habilidades práticas em ciência de dados.
Assim como um químico aprende como limpar seus tudos de insaio e organizar seu laboratório, você aprenderá como limpar seus dados e gerar gráficos --- além de muitas outras coisas.
São essas habilidades que permitem que a ciência de dados realmente aconteça, e aqui você encontrará as melhores práticas para fazer cada uma dessas coisas com R.
Você aprenderá também como usar a gramática de gráficos, literalmente programando de forma reproduzível suas pesquisas e análises salvando dessa forma bastante tempo.
Você também aprenderá como gerenciar recursos cognitivos para facilitar descobertas quando estiver manipulando, visualizando e explorando dados.

Esse website é, e sempre será livre, licenciado sobre a licença [CC BY-NC-ND 3.0](https://creativecommons.org/licenses/by-nc-nd/3.0/us/).
Se você preferir uma cópia física deste livro, você pode comprar a primeira edição na [Amazon](https://amzn.to/2aHLAQ1), ou esperar até no meio de 2023 pela segunda edição.
Se você apreciar a leitura dessa versão livre e quiser fazer uma doação como forma de retribuição, por favor faça uma doação para [Kākāpō Recovery](https://www.doc.govt.nz/kakapo-donate): o [kākāpō](https://www.youtube.com/watch?v=9T1vfsHYiKY) (que aparece na capa de R4DS) é um papagaio em estado crítido de extinção na Nova Zelândia; Restam apenas 248 em vida hoje na natureza.

Se você fala outra língua, talvez você se interese por outras traduções livres disponíveis da primeira edição:

-   [Spanish](https://es.r4ds.hadley.nz)
-   [Italian](https://it.r4ds.hadley.nz)
-   [Turkish](https://tr.r4ds.hadley.nz)

Note também que R4DS usa [Código de Conduda do Colaborador](https://contributor-covenant.org/version/2/0/CODE_OF_CONDUCT.html).
Colaborando com este livro, você estará aceitando esses termos.

## Reconhecimentos {.unnumbered}

R4DS é hospedado por <https://www.netlify.com> como parte de seu suporte a software de código aberto e suas comunidades.
